version: "3.9"

services:
  db:
    image: docker.io/library/postgres:16-alpine
    container_name: demo_dbs
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demodb
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d:ro
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Containerfile
    container_name: demo_apis
    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: demodb
      PORT: 3000

    ports:
      - "3008:3000"

    # 🔥 THIS ENABLES LIVE CODE SYNC
    volumes:
      - ./src:/app/src
      # - /app/node_modules   # not needed since mounting only src

    # 🔥 RUN DEV MODE
    command: npm run dev

volumes:
  pg_data: